### PR TITLE
Fix audio display for document tool - refs #4754

### LINKED ISSUE #4754: [C2] Show icon and correct player for audio files
When a user click on a file the controls are broken. A black bar show but no controls to play and pause the audio are shown. In addition, the icon of the audio file is a generic file icon.

### PR DESCRIPTION
**Pull request by daniboygg**
Fix #4754

### CODE REVIEW

File: assets/vue/components/documents/DocumentEntry.vue [hunk 1]
```diff
@@ -52,6 +52,9 @@ const dataType = computed(() => {
   if (isVideo(props.data)) {
     return 'video'
   }
+  if (isAudio(props.data)) {
+    return 'video'
+  }
```
Comment (daniboygg) [inline assets/vue/components/documents/DocumentEntry.vue:57]: This property is set in :data-type="dataType". I couldn't find anything in documentation about audio. I couldn't use iframe and set the height of controls either. This approach works but show controls like a video. 

It's not ideal but at least user can see the audio controls.
